version: '3.7'

services:
  postgres:
    env_file: .env.dev
    image: postgres:12
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}

  bloom-api:
    env_file: .env.dev
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    container_name: bloom-api
    volumes:
      - ./src:/usr/app/src
      - ./nodemon.json:/usr/app/nodemon.json
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    command: npm run start:dev
