version: '3.7'

services:
  bloom-api-test:
    ## Uses the dev environment variables.
    env_file: .env.dev
    build:
      context: .
      dockerfile: Dockerfile
      ## Targetting the test stage of the Dockerfile.
      target: test
    command: dockerize
      -wait tcp://db:${DB_PORT} -wait tcp://bloom-api:8080 -timeout 30s
      npx jest --group=integration
    container_name: bloom-api-test
    depends_on:
      - db
      - bloom-api
