// ## BUS EVENTS - Handles all of the Event Emitter events.

export enum BusEvent {
  EMAIL_EVENT = 'EMAIL_EVENT',
  GOOGLE_EVENT = 'GOOGLE_EVENT',
  MAILCHIMP_EVENT = 'MAILCHIMP_EVENT',
  TASK_EVENT = 'TASK_EVENT'
}

export enum EmailEvent {
  ACCEPTED_INTO_COMMUNITY = 'ACCEPTED_INTO_COMMUNITY',
  APPLY_TO_COMMUNITY = 'APPLY_TO_COMMUNITY',
  APPLY_TO_COMMUNITY_ADMINS = 'APPLY_TO_COMMUNITY_ADMINS',
  CREATE_EVENT_COORDINATOR = 'CREATE_EVENT_COORDINATOR',
  DELETE_EVENT_COORDINATOR = 'DELETE_EVENT_COORDINATOR',
  DELETE_EVENT_GUESTS = 'DELETE_EVENT_GUESTS',
  DELETE_MEMBERS = 'DELETE_MEMBERS',
  DEMOTE_MEMBERS = 'DEMOTE_MEMBERS',
  EVENT_REMINDER = 'EVENT_REMINDER',
  EVENT_RSVP = 'EVENT_RSVP',
  INVITE_MEMBERS = 'INVITE_MEMBERS',
  LOGIN_LINK = 'LOGIN_LINK',
  PROMOTE_MEMBERS = 'PROMOTE_MEMBERS'
}

export enum GoogleEvent {
  ADD_CALENDAR_EVENT_ATTENDEE = 'ADD_CALENDAR_EVENT_ATTENDEE',
  CREATE_CALENDAR_EVENT = 'CREATE_CALENDAR_EVENT',
  DELETE_CALENDAR_EVENT = 'DELETE_CALENDAR_EVENT',
  DELETE_CALENDAR_EVENT_ATTENDEE = 'DELETE_CALENDAR_EVENT_ATTENDEE',
  UPDATE_CALENDAR_EVENT = 'UPDATE_CALENDAR_EVENT'
}

export enum TaskEvent {
  EVENT_REMINDER_1_DAY = 'EVENT_REMINDER_1_DAY',
  EVENT_REMINDER_1_HOUR = 'EVENT_REMINDER_1_HOUR'
}

export enum VerifyEvent {
  JOIN_EVENT = 'JOIN_EVENT',
  LOGIN = 'LOGIN'
}
