export enum EmailEvent {
  CONNECT_INTEGRATIONS = 'CONNECT_INTEGRATIONS',
  CREATE_EVENT_COORDINATOR = 'CREATE_EVENT_COORDINATOR',
  LOGIN_LINK = 'LOGIN_LINK',
  PAYMENT_RECEIPT = 'PAYMENT_RECEIPT'
}

export enum FlushEvent {
  ACCEPT_APPLICANTS = 'ACCEPT_APPLICANTS',
  ACCEPT_INVITATIONS = 'ACCEPT_INVITATIONS',
  ADD_MEMBERS = 'ADD_MEMBERS',
  ADD_TO_MAILCHIMP = 'ADD_TO_MAILCHIMP',
  APPLY_FOR_MEMBERSHIP = 'APPLY_FOR_MEMBERSHIP',
  ATTACH_GOOGLE_CALENDAR_EVENT = 'ATTACH_GOOGLE_CALENDAR_EVENT',
  CREATE_COMMUNITY = 'CREATE_COMMUNITY',
  CREATE_EVENT = 'CREATE_EVENT',
  CREATE_EVENT_ATTENDEE = 'CREATE_EVENT_ATTENDEE',
  CREATE_EVENT_GUEST = 'CREATE_EVENT_GUEST',
  CREATE_EVENT_WATCH = 'CREATE_EVENT_WATCH',
  CREATE_MEMBER_REFRESH = 'CREATE_MEMBER_REFRESH',
  CREATE_MEMBER_TYPES = 'CREATE_MEMBER_TYPES',
  CREATE_STRIPE_CUSTOMER = 'CREATE_STRIPE_CUSTOMER',
  CREATE_STRIPE_PRODUCTS = 'CREATE_STRIPE_PRODUCTS',
  CREATE_SUBSCRIPTION = 'CREATE_SUBSCRIPTION',
  DELETE_EVENT = 'DELETE_EVENT',
  DELETE_EVENT_GUEST = 'DELETE_EVENT_GUEST',
  DELETE_MEMBERS = 'DELETE_MEMBERS',
  DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION',
  DEMOTE_MEMBERS = 'DEMOTE_MEMBERS',
  IGNORE_APPLICANTS = 'IGNORE_APPLICANTS',
  IMPORT_COMMUNITY_CSV = 'IMPORT_COMMUNITY_CSV',
  ON_FLUSH = 'ON_FLUSH',
  PROMOTE_MEMBERS = 'PROMOTE_MEMBERS',
  RESTORE_MEMBERS = 'RESTORE_MEMBERS',
  STORE_MAILCHIMP_TOKEN = 'STORE_MAILCHIMP_TOKEN',
  STORE_STRIPE_ACCOUNT = 'STORE_STRIPE_ACCOUNT',
  UPDATE_EVENT = 'UPDATE_EVENT',
  UPDATE_EVENT_RECORDING_LINK = 'UPDATE_EVENT_RECORDING_LINK',
  UPDATE_INTEGRATIONS = 'UPDATE_INTEGRATIONS',
  UPDATE_MAILCHIMP = 'UPDATE_MAILCHIMP',
  UPDATE_MEMBER = 'UPDATE_MEMBER',
  UPDATE_PAYMENT_METHOD = 'UPDATE_PAYMENT_METHOD',
  UPDATE_QUESTION = 'UPDATE_QUESTION',
  UPDATE_REFRESH_TOKEN = 'UPDATE_REFRESH_TOKEN',
  UPDATE_USER = 'UPDATE_USER'
}

export enum LoggerEvent {
  START_SERVER = 'START_SERVER'
}

export enum MiscEvent {
  ADD_GOOGLE_CALENDAR_EVENT_ATTENDEE = 'ADD_GOOGLE_CALENDAR_EVENT_ATTENDEE',
  CREATE_GOOGLE_CALENDAR_EVENT = 'CREATE_GOOGLE_CALENDAR_EVENT',
  DELETE_GOOGLE_CALENDAR_EVENT = 'DELETE_GOOGLE_CALENDAR_EVENT',
  DELETE_GOOGLE_CALENDAR_EVENT_ATTENDEE = 'DELETE_GOOGLE_CALENDAR_EVENT_ATTENDEE',
  EMAIL_FAILED = 'EMAIL_FAILED',
  SEND_EMAIL = 'SEND_EMAIL',
  UPDATE_GOOGLE_CALENDAR_EVENT = 'UPDATE_GOOGLE_CALENDAR_EVENT'
}

// Used for caching purposes (building the keys).
export enum QueryEvent {
  GET_APPLICATION = 'GET_APPLICATION',
  GET_COMMUNITY = 'GET_COMMUNITY',
  GET_EVENT = 'GET_EVENT',
  GET_INTEGRATIONS = 'GET_INTEGRATIONS',
  GET_MEMBER = 'GET_MEMBER',
  GET_USER = 'GET_USER',

  GET_QUESTIONS = 'GET_QUESTIONS',
  GET_PAYMENTS = 'GET_PAYMENTS',
  GET_TYPES = 'GET_TYPES',

  GET_ACTIVE_DUES_GROWTH = 'GET_ACTIVE_DUES_GROWTH',
  GET_ACTIVE_MEMBERS_GROWTH = 'GET_ACTIVE_MEMBERS_GROWTH',
  GET_ACTIVE_MEMBERS_SERIES = 'GET_ACTIVE_MEMBERS_SERIES',
  GET_APPLICANTS = 'GET_APPLICANTS',
  GET_DATABASE = 'GET_DATABASE',
  GET_DIRECTORY = 'GET_DIRECTORY',
  GET_EVENT_ATTENDEES = 'GET_EVENT_ATTENDEES',
  GET_EVENT_ATTENDEES_SERIES = 'GET_EVENT_ATTENDEES_SERIES',
  GET_EVENT_GUESTS = 'GET_EVENT_GUESTS',
  GET_EVENT_WATCHES = 'GET_EVENT_WATCHES',
  GET_MEMBER_DATA = 'GET_MEMBER_DATA',
  GET_MEMBERS = 'GET_MEMBERS',
  GET_OWNER = 'GET_OWNER',
  GET_PAST_EVENTS = 'GET_PAST_EVENTS',
  GET_PAST_EVENT_ATTENDEES = 'GET_PAST_EVENT_ATTENDEES',
  GET_PAST_EVENT_GUESTS = 'GET_PAST_EVENT_GUESTS',
  GET_PAST_EVENT_WATCHES = 'GET_PAST_EVENT_WATCHES',
  GET_TOTAL_DUES_COLLECTED = 'GET_TOTAL_DUES_COLLECTED',
  GET_TOTAL_DUES_GROWTH = 'GET_TOTAL_DUES_GROWTH',
  GET_TOTAL_DUES_SERIES = 'GET_TOTAL_DUES_SERIES',
  GET_TOTAL_MEMBERS_GROWTH = 'GET_TOTAL_MEMBERS_GROWTH',
  GET_TOTAL_MEMBERS_SERIES = 'GET_TOTAL_MEMBERS_SERIES',
  GET_UPCOMING_EVENTS = 'GET_UPCOMING_EVENTS',
  GET_UPCOMING_EVENT_GUESTS = 'GET_UPCOMING_EVENT_GUESTS'
}
