table:
  name: applications
  schema: public
object_relationships:
  - name: community
    using:
      foreign_key_constraint_on: community_id
array_relationships:
  - name: ranked_questions
    using:
      foreign_key_constraint_on:
        column: application_id
        table:
          name: ranked_questions
          schema: public
select_permissions:
  - permission:
      columns:
        - id
        - created_at
        - deleted_at
        - updated_at
        - description
        - title
        - community_id
      filter: {}
    role: guest
