export enum QuestionCategory {
  DUES_STATUS = 'DUES_STATUS',
  EMAIL = 'EMAIL',
  FIRST_NAME = 'FIRST_NAME',
  GENDER = 'GENDER',
  JOINED_AT = 'JOINED_AT',
  LAST_NAME = 'LAST_NAME',
  MEMBERSHIP_TYPE = 'MEMBERSHIP_TYPE'
}

export enum QuestionLevel {
  APPLICANT = 'APPLICANT',
  APPLICATION = 'APPLICATION',
  APPLICATION_ONLY = 'APPLICATION_ONLY',
  DIRECTORY = 'DIRECTORY',
  MEMBER_PROFILE = 'MEMBER_PROFILE'
}

export enum QuestionType {
  LONG_TEXT = 'LONG_TEXT',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  MULTIPLE_SELECT = 'MULTIPLE_SELECT',
  SHORT_TEXT = 'SHORT_TEXT'
}
