import { Authorized, Field, Int, ObjectType } from 'type-graphql';
import {
  ArrayType,
  BeforeCreate,
  Entity,
  Enum,
  ManyToOne,
  Property
} from '@mikro-orm/core';

import BaseEntity from '@core/db/BaseEntity';
import { Community } from '@entities/entities';
import { QuestionCategory, QuestionType } from './Question.types';

@ObjectType()
@Entity()
export default class Question extends BaseEntity {
  @Field(() => Boolean)
  @Property({ type: Boolean })
  adminOnly = false;

  @Field(() => Boolean)
  @Property({ type: Boolean })
  autoGenerated = false;

  // If the question is a special question, we have to store it in a different
  // fashion. For example, 'EMAIL' would be stored on the user, NOT the
  // member.
  @Field(() => String, { nullable: true })
  @Enum({ items: () => QuestionCategory, nullable: true, type: String })
  category: QuestionCategory;

  @Field({ nullable: true })
  @Property({ nullable: true, type: 'text' })
  description: string;

  // True if this is only needed for the application decision.
  @Field(() => Boolean)
  @Property({ type: Boolean })
  onlyInApplication = false;

  // In the applicant card if it's important to the ADMIN.
  @Authorized('ADMIN')
  @Field(() => Boolean)
  @Property({ type: Boolean })
  inApplicantCard = false;

  // Will only be non-null if the type is MULTIPLE_CHOICE or MULTIPLE_SELECT.
  @Field(() => [String], { nullable: true })
  @Property({ nullable: true, type: ArrayType })
  options: string[];

  // Order that the question appears. Similar to an index in an array.
  @Field(() => Int)
  @Property()
  order: number;

  @Field(() => Boolean)
  @Property({ type: Boolean })
  required = true;

  @Field()
  @Property()
  title: string;

  @Field(() => String, { nullable: true })
  @Enum({ items: () => QuestionType, nullable: true, type: String })
  type: QuestionType;

  // ## LIFECYCLE

  @BeforeCreate()
  beforeCreate() {
    if (
      [
        QuestionCategory.EMAIL,
        QuestionCategory.FIRST_NAME,
        QuestionCategory.LAST_NAME
      ].includes(this.category)
    ) {
      this.type = QuestionType.SHORT_TEXT;
    }

    if (
      [
        QuestionCategory.DUES_STATUS,
        QuestionCategory.JOINED_AT,
        QuestionCategory.MEMBERSHIP_TYPE
      ].includes(this.category)
    ) {
      this.autoGenerated = true;
    }

    if (
      [QuestionCategory.DUES_STATUS, QuestionCategory.MEMBERSHIP_TYPE].includes(
        this.category
      )
    ) {
      this.type = QuestionType.MULTIPLE_CHOICE;
    }

    if (this.category === QuestionCategory.GENDER) {
      this.options = ['Male', 'Female', 'Non-Binary', 'Prefer Not to Say'];
    }

    if (this.category === QuestionCategory.MEMBERSHIP_TYPE) {
      this.inApplicantCard = false;
      this.options = this.community.types.getItems().map(({ name }) => name);
    }
  }

  // ## RELATIONSHIPS

  @Field(() => Community)
  @ManyToOne(() => Community)
  community: Community;
}
