import { Field, ObjectType } from 'type-graphql';
import {
  ArrayType,
  BeforeCreate,
  Entity,
  Enum,
  ManyToOne,
  Property
} from '@mikro-orm/core';

import BaseEntity from '@core/db/BaseEntity';
import { Community } from '@entities/entities';

export enum QuestionCategory {
  DUES_STATUS = 'DUES_STATUS',
  EMAIL = 'EMAIL',
  FIRST_NAME = 'FIRST_NAME',
  GENDER = 'GENDER',
  JOINED_AT = 'JOINED_AT',
  LAST_NAME = 'LAST_NAME',
  MEMBERSHIP_TYPE = 'MEMBERSHIP_TYPE'
}

export enum QuestionType {
  LONG_TEXT = 'LONG_TEXT',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  MULTIPLE_SELECT = 'MULTIPLE_SELECT',
  SHORT_TEXT = 'SHORT_TEXT'
}

@ObjectType()
@Entity()
export default class Question extends BaseEntity {
  @Field({ defaultValue: true })
  @Property()
  adminOnly: boolean = false;

  @Field({ defaultValue: false })
  @Property()
  autoGenerated: boolean = false;

  // If the question is a special question, we have to store it in a different
  // fashion. For example, 'EMAIL' would be stored on the user, NOT the
  // member.
  @Field(() => String, { nullable: true })
  @Enum({ items: () => QuestionCategory, nullable: true, type: String })
  category?: QuestionCategory;

  @Field({ nullable: true })
  @Property({ nullable: true, type: 'text' })
  description?: string;

  // Will only be non-null if the type is MULTIPLE_CHOICE or MULTIPLE_SELECT.
  @Field(() => [String], { nullable: true })
  @Property({ nullable: true, type: ArrayType })
  options?: string[];

  @Field()
  @Property()
  required: boolean = true;

  @Field()
  @Property()
  title: string;

  @Field(() => String, { nullable: true })
  @Enum({ items: () => QuestionType, nullable: true, type: String })
  type: QuestionType;

  // ## LIFECYCLE

  @BeforeCreate()
  beforeCreate() {
    if (
      [
        QuestionCategory.EMAIL,
        QuestionCategory.FIRST_NAME,
        QuestionCategory.LAST_NAME
      ].includes(this.category)
    ) {
      this.type = QuestionType.SHORT_TEXT;
    }

    if (
      [
        QuestionCategory.DUES_STATUS,
        QuestionCategory.JOINED_AT,
        QuestionCategory.MEMBERSHIP_TYPE
      ].includes(this.category)
    ) {
      this.autoGenerated = true;
    }

    if (
      [
        QuestionCategory.DUES_STATUS,
        QuestionCategory.GENDER,
        QuestionCategory.MEMBERSHIP_TYPE
      ].includes(this.category)
    ) {
      this.type = QuestionType.MULTIPLE_CHOICE;
    }

    if (this.category === QuestionCategory.GENDER) {
      this.options = ['Male', 'Female', 'Non-Binary', 'Prefer Not to Say'];
    }

    if (this.category === QuestionCategory.MEMBERSHIP_TYPE) {
      this.options = this.community.types.getItems().map(({ name }) => name);
    }
  }

  // ## RELATIONSHIPS

  @Field(() => Community)
  @ManyToOne(() => Community)
  community: Community;
}
